AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECR Repository for ECS Blue/Green deployment'

Parameters:
  ProjectName:
    Type: String
    Default: 'ecs-bg-deploy'

Resources:
  # ECR Repository
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${ProjectName}-app'

Outputs:
  ECRRepository:
    Description: ECR Repository URI
    Value: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepository}'
    Export:
      Name: !Sub '${ProjectName}-ECRRepository'